mieq.c: add missing include
Fixes this error:

  mieq.c: In function ‘mieqProcessInputEvents’:
  mieq.c:162:11: error: ‘DPMSPowerLevel’ undeclared (first use in this function)
    else if (DPMSPowerLevel != DPMSModeOn)
             ^~~~~~~~~~~~~~

Signed-off-by: Mario Trangoni <mjtrangoni@gmail.com>