Correct nxproxy manpage also: --help -> -help
xorg-server does not follow the convention of using 2 dashes,
and apparently nx-libs doesn't either.

Note that --help does produce the help output. However, it
produces this additional output after it:

Error: NX transport initialization failed.

Therefore, we should instruct users to call -help instead.