dix: Fix a warning about GetTimeInMillis return value in XFont2.
Ported over from XOrg Server:

    commit e1ccd0fa0e1081edf8a2c69ce6e8e3f67a4aecba
    Author: Emma Anholt <emma@anholt.net>
    Date:   Mon May 7 16:46:15 2018 -0700

        dix: Fix a warning about GetTimeInMillis return value in XFont2.

        Signed-off-by: Eric Anholt <eric@anholt.net>
        Reviewed-by: Adam Jackson <ajax@redhat.com>

This resolves the following issue when built with GCC-14 (and beyond):

    ../../dix/dixfonts.c: At top level:
    ../../dix/dixfonts.c:2485:27: error: initialization of âuint32_t (*)(void)â {aka âunsigned int (*)(void)â} from incompatible pointer type âCARD32 (*)(void)â {aka âlong unsigned int (*)(void)â} [-Wincompatible-pointer-types]
     2485 |     .get_time_in_millis = GetTimeInMillis,
          |