Correct manpages: --help -> -help
xorg-server does not follow the convention of using 2 dashes.

Note that --help does produce the help output. However, it
produces this additional output after it:

Error: Aborting session with 'Unrecognized option: --help'.
Session: Aborting session at 'Sun Jun 28 01:35:35 2015'.
Session: Session aborted at 'Sun Jun 28 01:35:35 2015'.

It also causes a return code of 1 rather than 0.

Therefore, we should instruct users to call -help instead.